---

- name: add smb share
  shell: |
    echo "Path: {{ args_smbshare_name }}"
    echo "Path: {{ args_smbshare_comment }}"
    echo "Path: {{ args_smbshare_path }}"
    echo "mode: {{ args_smbshare_mode }}"
    echo "mode: {{ args_smbshare_guest }}"
    line="[{{ args_smbshare_name }}]"
    count=$(cat /etc/samba/smb.conf | grep -x -F "$line" | wc -l)
    echo "count = $count"
    if [ $count -gt 0 ] ; then
      echo "NO CHANGE"
    else
      echo "[{{ args_smbshare_name }}]" >> /etc/samba/smb.conf
      echo "   comment = {{ args_smbshare_comment }}" >> /etc/samba/smb.conf
      echo "   path = {{ args_smbshare_path }}" >> /etc/samba/smb.conf
      echo "   read only = {{ args_smbshare_mode }}" >> /etc/samba/smb.conf
      echo "   browseable = yes" >> /etc/samba/smb.conf
      echo "   guest ok = {{ args_smbshare_guest }}" >> /etc/samba/smb.conf
      service smbd restart
      echo "CHANGED"
    fi
  register: result
  changed_when: '"CHANGED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_smbshare_ipaddress }}"
  become: true
