---

++++++++++++++ NEED tot be changed see SMB +++++++++++++++++++++++++++

- name: add nfs share
  shell: |
    echo "Path: {{ args_nfsshare_path }}"
    echo "mode: {{ args_nfsshare_mode }}"
    echo "target: {{ args_nfsshare_target }}"
    line="{{ args_nfsshare_path }} {{ args_nfsshare_target }}({{ args_nfsshare_mode }},sync,no_subtree_check)"
    count=$(cat /etc/exports | grep -x -F "$line" | wc -l)
    echo "count = $count"
    #echo "line [$line]"
    #echo "---------------------------"
    #cat /etc/exports
    #echo "---------------------------"
    if [ $count -gt 0 ] ; then
      echo "NO CHANGE"
    else
      echo $line >> /etc/exports
      exportfs -a
      echo "CHANGED"
    fi
  register: result
  changed_when: '"CHANGED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_nfsshare_ipaddress }}"
  become: true

