---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - nfs-kernel-server 

- name: set firewall
  shell: |
    command=$(which ufw)
    if [ $command ] ; then
      ufw allow nfs
      echo "set ufw"
    else
      echo "ufw not present"
    fi
