---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - cifs-utils
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: .smbcred.j2
    dest: "/home/{{ prop_admin_username }}/.{{ prop_basename }}/.smbcred"
    owner: "{{ prop_admin_username }}"
    group: "{{ prop_admin_groupname }}"
    mode: '0400'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true
