---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - samba 

- name: set firewall
  shell: |
    ufw allow samba
