---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - samba 
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: set firewall
  shell: |
    command=$(which ufw)
    if [ $command ] ; then
      ufw allow nfs
      echo "set ufw"
    else
      echo "ufw not present"
    fi
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true
