---

- name: "Playbook: Condigure SMB client"
  hosts: "{{ args_host }}"
  gather_facts: false
  become: true
  vars:
    ansible_host: "{{ prop_ipaddress }}"

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.linux.installsmbclient
      vars:
        args_smbclient_ipaddress: "{{ prop_ipaddress }}"
        args_smbclient_username: "{{ prop_admin_username }}"
        args_smbclient_password: "{{ prop_admin_password }}"
        args_smbclient_groupname: "{{ prop_admin_groupname }}"
        args_smbclient_basename: "{{ prop_basename }}"

  tasks:
    - ansible.builtin.include_role:
        name: alex.linux.mountsmbshare
      vars:
        args_mountsmb_ipaddress: "{{ prop_ipaddress }}"
        args_mountsmb_ipaddress: "{{ prop_ipaddress }}"
        args_mountsmb_mounts: "{{ prop_smb_mounts }}"
        args_mountsmb_username: "{{ prop_admin_username }}"
        args_mountsmb_basename: "{{ prop_basename }}"
