---

- name: "Playbook: Condigure SMB client"
  hosts: "{{ args_host }}"
  gather_facts: false
  become: true
  vars:
    ansible_host: "{{ prop_ipaddress }}"

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.linux.installsmbserver

    - ansible.builtin.include_role:
        name: alex.linux.setsmbuser

    - ansible.builtin.include_role:
        name: alex.linux.addsmbshare

    - ansible.builtin.include_role:
        name: alex.linux.installsmbclient

    - ansible.builtin.include_role:
        name: alex.linux.mountsmbshare
