---

- name: "Playbook: Test all playbooks"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
#    - ansible.builtin.include_role:
#        name: alex.linux.installnfsserver
#      vars:
#        args_nfsserver_ipaddress: "{{ prop_ipaddress }}"

#    - ansible.builtin.include_role:
#        name: alex.linux.addnfsshare
#      vars:
#        args_nfsshare_ipaddress: "{{ prop_ipaddress }}"
#        args_nfsshare_path: /path
#        args_nfsshare_mode: rw
#        args_nfsshare_target: "*"

    - ansible.builtin.include_role:
        name: alex.linux.installsmbserver
      vars:
        args_smbserver_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.linux.setsmbuser
      vars:
        args_smbserver_ipaddress: "{{ prop_ipaddress }}"
        args_smbuser_user: "{{ prop_admin_username }}"
        args_smbuser_password: "{{ prop_admin_password }}"

    - ansible.builtin.include_role:
        name: alex.linux.addsmbshare
      vars:
        args_smbshare_ipaddress: "{{ prop_ipaddress }}"
        args_smbshare_name: "alex"
        args_smbshare_comment: "alex share"
        args_smbshare_path: "/alex"
        args_smbshare_mode: "no"
        args_smbshare_guest: "no"

    - ansible.builtin.include_role:
        name: alex.linux.installsmbclient
      vars:
        args_smbclient_ipaddress: "{{ prop_ipaddress }}"
        args_smbclient_username: "{{ prop_admin_username }}"
        args_smbclient_password: "{{ prop_admin_password }}"
        args_smbclient_groupname: "{{ prop_admin_groupname }}"
        args_smbclient_basename: "{{ prop_basename }}"

    - ansible.builtin.include_role:
        name: alex.linux.mountsmbshare
      vars:
        args_mountsmb_ipaddress: "{{ prop_ipaddress }}"
        args_mountsmb_ipaddress: "{{ prop_ipaddress }}"
        args_mountsmb_mounts: "{{ prop_smb_mounts }}"
        args_mountsmb_username: "{{ prop_admin_username }}"
        args_mountsmb_basename: "{{ prop_basename }}"
